/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Principal;

import static Principal.RelojDigital.letras;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.IOException;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;


/**
 *
 * @author Personal
 */
public class RelojMaya extends javax.swing.JFrame implements Runnable {
    String hora,minutos,segundos,ampm;
    Calendar calendario;
    Thread h1;
    int bandera=0,seg=0,min,hr;
 
        
        
   
    /**
     * Creates new form RelojMaya
     */
    public RelojMaya() throws IOException {
        
        h1=new Thread(this);
        InicializarConfiguracion();
        
        initComponents();
        
       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButtonIniciar = new javax.swing.JButton();
        jButtonDetener = new javax.swing.JButton();
        jLabelHora = new javax.swing.JLabel();
        jLabelMinutos = new javax.swing.JLabel();
        jLabelSegundos = new javax.swing.JLabel();
        jLabelImagenMinutos = new javax.swing.JLabel();
        jLabelImagenSegundos = new javax.swing.JLabel();
        jLabelImagenHora = new javax.swing.JLabel();
        jPanelnum32 = new javax.swing.JPanel();
        jPanelnum8 = new javax.swing.JPanel();
        jPanelnum16 = new javax.swing.JPanel();
        jPanelnum4 = new javax.swing.JPanel();
        jPanelnum2 = new javax.swing.JPanel();
        jPanelnum1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        jLabel3.setText("jLabel3");

        setTitle("Reloj Maya");

        jButtonIniciar.setText("Iniciar");
        jButtonIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIniciarActionPerformed(evt);
            }
        });

        jButtonDetener.setText("Detener");
        jButtonDetener.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDetenerActionPerformed(evt);
            }
        });

        jLabelHora.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelHora.setText("Hora");

        jLabelMinutos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelMinutos.setText("Minutos");

        jLabelSegundos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelSegundos.setText("Segundos");

        jLabelImagenMinutos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelImagenMinutos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabelImagenSegundos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelImagenSegundos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabelImagenHora.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelImagenHora.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanelnum32.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        javax.swing.GroupLayout jPanelnum32Layout = new javax.swing.GroupLayout(jPanelnum32);
        jPanelnum32.setLayout(jPanelnum32Layout);
        jPanelnum32Layout.setHorizontalGroup(
            jPanelnum32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 55, Short.MAX_VALUE)
        );
        jPanelnum32Layout.setVerticalGroup(
            jPanelnum32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 56, Short.MAX_VALUE)
        );

        jPanelnum8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        javax.swing.GroupLayout jPanelnum8Layout = new javax.swing.GroupLayout(jPanelnum8);
        jPanelnum8.setLayout(jPanelnum8Layout);
        jPanelnum8Layout.setHorizontalGroup(
            jPanelnum8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 55, Short.MAX_VALUE)
        );
        jPanelnum8Layout.setVerticalGroup(
            jPanelnum8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 56, Short.MAX_VALUE)
        );

        jPanelnum16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        javax.swing.GroupLayout jPanelnum16Layout = new javax.swing.GroupLayout(jPanelnum16);
        jPanelnum16.setLayout(jPanelnum16Layout);
        jPanelnum16Layout.setHorizontalGroup(
            jPanelnum16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 55, Short.MAX_VALUE)
        );
        jPanelnum16Layout.setVerticalGroup(
            jPanelnum16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 56, Short.MAX_VALUE)
        );

        jPanelnum4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        javax.swing.GroupLayout jPanelnum4Layout = new javax.swing.GroupLayout(jPanelnum4);
        jPanelnum4.setLayout(jPanelnum4Layout);
        jPanelnum4Layout.setHorizontalGroup(
            jPanelnum4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 55, Short.MAX_VALUE)
        );
        jPanelnum4Layout.setVerticalGroup(
            jPanelnum4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 56, Short.MAX_VALUE)
        );

        jPanelnum2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        javax.swing.GroupLayout jPanelnum2Layout = new javax.swing.GroupLayout(jPanelnum2);
        jPanelnum2.setLayout(jPanelnum2Layout);
        jPanelnum2Layout.setHorizontalGroup(
            jPanelnum2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 55, Short.MAX_VALUE)
        );
        jPanelnum2Layout.setVerticalGroup(
            jPanelnum2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 56, Short.MAX_VALUE)
        );

        jPanelnum1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        javax.swing.GroupLayout jPanelnum1Layout = new javax.swing.GroupLayout(jPanelnum1);
        jPanelnum1.setLayout(jPanelnum1Layout);
        jPanelnum1Layout.setHorizontalGroup(
            jPanelnum1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 55, Short.MAX_VALUE)
        );
        jPanelnum1Layout.setVerticalGroup(
            jPanelnum1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 56, Short.MAX_VALUE)
        );

        jLabel2.setText("32");

        jLabel4.setText("16");

        jLabel5.setText("4");

        jLabel6.setText("8");

        jLabel7.setText("2");

        jLabel8.setText("1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonDetener, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonIniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelImagenHora, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabelHora, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabelMinutos, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                        .addComponent(jLabelSegundos, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelImagenMinutos, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabelImagenSegundos, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel8)
                                .addGap(33, 33, 33))))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanelnum32, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelnum16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelnum8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelnum4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelnum2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelnum1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
            .addGroup(layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(jLabel2)
                .addGap(57, 57, 57)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jButtonIniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonDetener, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelImagenMinutos, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelImagenSegundos, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelImagenHora, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelMinutos)
                    .addComponent(jLabelSegundos)
                    .addComponent(jLabelHora))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelnum32, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelnum8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelnum16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelnum4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelnum2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelnum1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonDetenerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDetenerActionPerformed
        // TODO add your handling code here:
        if(bandera==1){
          h1.suspend();
         bandera=2;
        }
    }//GEN-LAST:event_jButtonDetenerActionPerformed

    private void jButtonIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIniciarActionPerformed
        // TODO add your handling code here: 
         if(bandera==0){  
        h1.start();
         
        bandera=1;
        }else{
        h1.resume();
        bandera=1;
        } 
    }//GEN-LAST:event_jButtonIniciarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RelojMaya.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RelojMaya.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RelojMaya.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RelojMaya.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
    
                       
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new RelojMaya().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(RelojMaya.class.getName()).log(Level.SEVERE, null, ex);
                }
                
            }
              
        });
      
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDetener;
    private javax.swing.JButton jButtonIniciar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelHora;
    private javax.swing.JLabel jLabelImagenHora;
    private javax.swing.JLabel jLabelImagenMinutos;
    private javax.swing.JLabel jLabelImagenSegundos;
    private javax.swing.JLabel jLabelMinutos;
    private javax.swing.JLabel jLabelSegundos;
    public static javax.swing.JPanel jPanelnum1;
    public static javax.swing.JPanel jPanelnum16;
    public static javax.swing.JPanel jPanelnum2;
    public static javax.swing.JPanel jPanelnum32;
    public static javax.swing.JPanel jPanelnum4;
    public static javax.swing.JPanel jPanelnum8;
    // End of variables declaration//GEN-END:variables
 public  void InicializarConfiguracion(){
         
       Toolkit tool= Toolkit.getDefaultToolkit();
       Dimension dimensionScreen=tool.getScreenSize();
        dimensionScreen.getHeight();
        dimensionScreen.getWidth();
        int width=500;
        int heigh=350;
        setSize(width, heigh);
        setLocation((dimensionScreen.width-width)/2, (dimensionScreen.height-heigh)/2);
        setVisible(true);
        Image icon =tool.getImage("src/Principal/icon.png");
        setIconImage(icon);
      
       
    }

    @Override
    public void run() {
      Thread ct=Thread.currentThread();
        while(ct==h1){     
        calcula();
        
         seg=Integer.parseInt(segundos);
         min=Integer.parseInt(minutos);
         hr=Integer.parseInt(hora);
       semaforo(seg);
        jLabelImagenSegundos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Principal/Simbologia/"+seg+".PNG")));
        jLabelImagenHora.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Principal/Simbologia/"+hr+".PNG")));
        jLabelImagenMinutos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Principal/Simbologia/"+min+".PNG")));
        
        System.out.println(seg);
        
        }

                
        try{
        Thread.sleep(1000);
        }catch(InterruptedException e){
        
        }
        
       }    
    
     
    
       public void calcula(){
        Calendar calendario=new GregorianCalendar();
        Date HoraActual=new Date();
        
        calendario.setTime(HoraActual);
        ampm= calendario.get(Calendar.AM_PM)==Calendar.AM?"AM":"PM";
        
        if(ampm.equals("PM")){
        int h=calendario.get(Calendar.HOUR_OF_DAY);
        hora =h>9?""+h:"0"+h;      
        }else{
        hora=calendario.get(Calendar.HOUR_OF_DAY)>9?""+calendario.get(Calendar.HOUR_OF_DAY):"0"+calendario.get(Calendar.HOUR_OF_DAY);
        }
        minutos=calendario.get(Calendar.MINUTE)>9?""+calendario.get(Calendar.MINUTE):"0"+calendario.get(Calendar.MINUTE);
        segundos=calendario.get(Calendar.SECOND)>9?""+calendario.get(Calendar.SECOND):"0"+calendario.get(Calendar.SECOND);
    }
       
     public void semaforo(int seg){

         if(seg==0){
          jPanelnum1.setBackground(Color.black);
        jPanelnum2.setBackground(Color.black);
        jPanelnum4.setBackground(Color.black);
        jPanelnum8.setBackground(Color.black);
        jPanelnum16.setBackground(Color.black);
        jPanelnum32.setBackground(Color.black);
         }
         if(seg==1){
         jPanelnum1.setBackground(Color.red);
          jPanelnum2.setBackground(Color.black);
        jPanelnum4.setBackground(Color.black);
        jPanelnum8.setBackground(Color.black);
        jPanelnum16.setBackground(Color.black);
        jPanelnum32.setBackground(Color.black);
         }
         if(seg==2){
         jPanelnum2.setBackground(Color.red);
          jPanelnum1.setBackground(Color.black);
        jPanelnum4.setBackground(Color.black);
        jPanelnum8.setBackground(Color.black);
        jPanelnum16.setBackground(Color.black);
        jPanelnum32.setBackground(Color.black);
         }
         if(seg==3){
         jPanelnum1.setBackground(Color.red);
         jPanelnum2.setBackground(Color.red);
         jPanelnum4.setBackground(Color.black);
        jPanelnum8.setBackground(Color.black);
        jPanelnum16.setBackground(Color.black);
        jPanelnum32.setBackground(Color.black);
         }
         if(seg==4){
         jPanelnum4.setBackground(Color.red);
         jPanelnum1.setBackground(Color.black);
         jPanelnum2.setBackground(Color.black);
        jPanelnum8.setBackground(Color.black);
        jPanelnum16.setBackground(Color.black);
        jPanelnum32.setBackground(Color.black);
         }
         if(seg==5){
         jPanelnum1.setBackground(Color.red);
         jPanelnum4.setBackground(Color.red);
         jPanelnum2.setBackground(Color.black);
        jPanelnum8.setBackground(Color.black);
        jPanelnum16.setBackground(Color.black);
        jPanelnum32.setBackground(Color.black);
         }   
         if(seg==6){
         jPanelnum4.setBackground(Color.red);
         jPanelnum2.setBackground(Color.red);
         jPanelnum1.setBackground(Color.black);
        jPanelnum8.setBackground(Color.black);
        jPanelnum16.setBackground(Color.black);
        jPanelnum32.setBackground(Color.black);
         }
         if(seg==7){
         jPanelnum4.setBackground(Color.red);
         jPanelnum2.setBackground(Color.red);
         jPanelnum1.setBackground(Color.red);
         jPanelnum8.setBackground(Color.black);
        jPanelnum16.setBackground(Color.black);
        jPanelnum32.setBackground(Color.black);
         }
         if(seg==8){
             jPanelnum4.setBackground(Color.black);
         jPanelnum2.setBackground(Color.black);
         jPanelnum1.setBackground(Color.black);
         jPanelnum8.setBackground(Color.red);
          jPanelnum16.setBackground(Color.black);
        jPanelnum32.setBackground(Color.black);
         }
         if(seg==9){
         jPanelnum1.setBackground(Color.red);
         jPanelnum2.setBackground(Color.black);
         jPanelnum4.setBackground(Color.black);
         jPanelnum8.setBackground(Color.red);  
         jPanelnum16.setBackground(Color.black);
         jPanelnum32.setBackground(Color.black);
         }
         if(seg==10){
         jPanelnum1.setBackground(Color.black);
         jPanelnum2.setBackground(Color.red);  
          jPanelnum4.setBackground(Color.black);
         jPanelnum8.setBackground(Color.red);
         jPanelnum16.setBackground(Color.black);
         jPanelnum32.setBackground(Color.black);
         }
         if(seg==11){
         jPanelnum1.setBackground(Color.red);
         jPanelnum2.setBackground(Color.red);  
         jPanelnum4.setBackground(Color.black);
         jPanelnum8.setBackground(Color.red);
          jPanelnum16.setBackground(Color.black);
         jPanelnum32.setBackground(Color.black);
         }
         if(seg==12){
              jPanelnum1.setBackground(Color.black);
         jPanelnum2.setBackground(Color.black);  
         jPanelnum4.setBackground(Color.red);
         jPanelnum8.setBackground(Color.red);
          jPanelnum16.setBackground(Color.black);
         jPanelnum32.setBackground(Color.black);
         }
         if(seg==13){
        jPanelnum1.setBackground(Color.red);
          jPanelnum2.setBackground(Color.black); 
        jPanelnum4.setBackground(Color.red);
        jPanelnum8.setBackground(Color.red);
          jPanelnum16.setBackground(Color.black);
         jPanelnum32.setBackground(Color.black);
         }
         if(seg==14){
             jPanelnum1.setBackground(Color.black);
         jPanelnum2.setBackground(Color.red); 
         jPanelnum4.setBackground(Color.red);
         jPanelnum8.setBackground(Color.red);
          jPanelnum16.setBackground(Color.black);
         jPanelnum32.setBackground(Color.black);
         }
         if(seg==15){
         jPanelnum1.setBackground(Color.red);
         jPanelnum2.setBackground(Color.red);
         jPanelnum4.setBackground(Color.red);
         jPanelnum8.setBackground(Color.red);
         jPanelnum16.setBackground(Color.black);
         jPanelnum32.setBackground(Color.black);
         }
         
         if(seg==16){
               jPanelnum1.setBackground(Color.black);
        jPanelnum2.setBackground(Color.black);
        jPanelnum4.setBackground(Color.black);
        jPanelnum8.setBackground(Color.black);
        jPanelnum32.setBackground(Color.black);
         jPanelnum16.setBackground(Color.red);
         }
         if(seg==17){
         jPanelnum1.setBackground(Color.red);
           jPanelnum2.setBackground(Color.black);
        jPanelnum4.setBackground(Color.black);
        jPanelnum8.setBackground(Color.black);
         jPanelnum16.setBackground(Color.red);
          jPanelnum32.setBackground(Color.black);
         }
         if(seg==18){
             jPanelnum1.setBackground(Color.black);
              jPanelnum4.setBackground(Color.black);
        jPanelnum8.setBackground(Color.black);
         jPanelnum2.setBackground(Color.red);
         jPanelnum16.setBackground(Color.red);
         jPanelnum32.setBackground(Color.black);
         }
         if(seg==19){
         jPanelnum1.setBackground(Color.red);
         jPanelnum2.setBackground(Color.red);
         jPanelnum4.setBackground(Color.black);
        jPanelnum8.setBackground(Color.black);
         jPanelnum16.setBackground(Color.red);
         jPanelnum32.setBackground(Color.black);
         }
         if(seg==20){
              jPanelnum1.setBackground(Color.black);
         jPanelnum2.setBackground(Color.black);
         jPanelnum8.setBackground(Color.black);
         jPanelnum16.setBackground(Color.red);
         jPanelnum4.setBackground(Color.red);
          jPanelnum32.setBackground(Color.black);
         }
         if(seg==21){
               jPanelnum32.setBackground(Color.black);
             jPanelnum8.setBackground(Color.black);
             jPanelnum2.setBackground(Color.black);
          jPanelnum16.setBackground(Color.red);
         jPanelnum4.setBackground(Color.red);
         jPanelnum1.setBackground(Color.red);
         }
         if(seg==22){
              jPanelnum8.setBackground(Color.black);
             jPanelnum1.setBackground(Color.black);
               jPanelnum32.setBackground(Color.black);
          jPanelnum16.setBackground(Color.red);
         jPanelnum4.setBackground(Color.red);
         jPanelnum2.setBackground(Color.red);
         }
         if(seg==23){
             jPanelnum32.setBackground(Color.black);
              jPanelnum8.setBackground(Color.black);
          jPanelnum16.setBackground(Color.red);
         jPanelnum4.setBackground(Color.red);
         jPanelnum1.setBackground(Color.red);
         jPanelnum2.setBackground(Color.red);
         }
         if(seg==24){
             jPanelnum32.setBackground(Color.black);
          jPanelnum16.setBackground(Color.red);
         jPanelnum8.setBackground(Color.red);
         jPanelnum4.setBackground(Color.black);
         jPanelnum2.setBackground(Color.black);
         jPanelnum1.setBackground(Color.black);

         }
         if(seg==25){
             jPanelnum32.setBackground(Color.black);
            jPanelnum16.setBackground(Color.red);
         jPanelnum8.setBackground(Color.red);
         jPanelnum4.setBackground(Color.black);
         jPanelnum2.setBackground(Color.black);
         jPanelnum1.setBackground(Color.red);
         }
         if(seg==26){
             jPanelnum32.setBackground(Color.black);
            jPanelnum16.setBackground(Color.red);
         jPanelnum8.setBackground(Color.red);
         jPanelnum4.setBackground(Color.black);
         jPanelnum2.setBackground(Color.red);
         jPanelnum1.setBackground(Color.black);
         }
         if(seg==27){
             jPanelnum32.setBackground(Color.black);
          jPanelnum16.setBackground(Color.red);
         jPanelnum8.setBackground(Color.red);
         jPanelnum4.setBackground(Color.black);
         jPanelnum2.setBackground(Color.red);
          jPanelnum1.setBackground(Color.red);
         }
         if(seg==28){
             jPanelnum32.setBackground(Color.black);
              jPanelnum16.setBackground(Color.red);
         jPanelnum8.setBackground(Color.red);
         jPanelnum4.setBackground(Color.red);
         jPanelnum2.setBackground(Color.black);
         jPanelnum1.setBackground(Color.black);
      
         }
         if(seg==29){
             jPanelnum32.setBackground(Color.black);
         jPanelnum16.setBackground(Color.red);
         jPanelnum8.setBackground(Color.red);
         jPanelnum4.setBackground(Color.red);
         jPanelnum2.setBackground(Color.black);
         jPanelnum1.setBackground(Color.red);
         }
         if(seg==30){
             jPanelnum32.setBackground(Color.black);
          jPanelnum16.setBackground(Color.red);
         jPanelnum8.setBackground(Color.red);
         jPanelnum4.setBackground(Color.red);
         jPanelnum2.setBackground(Color.red);
         jPanelnum1.setBackground(Color.black);
         }
         if(seg==31){
             jPanelnum32.setBackground(Color.black);
         jPanelnum16.setBackground(Color.red);
         jPanelnum8.setBackground(Color.red);
         jPanelnum4.setBackground(Color.red);
         jPanelnum2.setBackground(Color.red);
         jPanelnum1.setBackground(Color.red);
         }
         if(seg==32){
          jPanelnum32.setBackground(Color.red);
             jPanelnum16.setBackground(Color.black);
         jPanelnum8.setBackground(Color.black);
         jPanelnum4.setBackground(Color.black);
         jPanelnum2.setBackground(Color.black);
         jPanelnum1.setBackground(Color.black);
         }
         if(seg==33){
          jPanelnum32.setBackground(Color.red);
           jPanelnum16.setBackground(Color.black);
         jPanelnum8.setBackground(Color.black);
         jPanelnum4.setBackground(Color.black);
         jPanelnum2.setBackground(Color.black);
          jPanelnum1.setBackground(Color.red);
         }
         if(seg==34){
          jPanelnum32.setBackground(Color.red);
           jPanelnum16.setBackground(Color.black);
         jPanelnum8.setBackground(Color.black);
         jPanelnum4.setBackground(Color.black);
         jPanelnum1.setBackground(Color.black);
          jPanelnum2.setBackground(Color.red);
         }
         if(seg==35){
          jPanelnum32.setBackground(Color.red);
           jPanelnum16.setBackground(Color.black);
         jPanelnum8.setBackground(Color.black);
         jPanelnum4.setBackground(Color.black);
          jPanelnum2.setBackground(Color.red);
          jPanelnum1.setBackground(Color.red);
         }
         if(seg==36){
         jPanelnum32.setBackground(Color.red);
          jPanelnum16.setBackground(Color.black);
         jPanelnum8.setBackground(Color.black);
         jPanelnum2.setBackground(Color.black);
         jPanelnum1.setBackground(Color.black);
          jPanelnum4.setBackground(Color.red);
         }
         if(seg==37){
               jPanelnum16.setBackground(Color.black);
         jPanelnum8.setBackground(Color.black);
         jPanelnum2.setBackground(Color.black);
          jPanelnum32.setBackground(Color.red);
          jPanelnum4.setBackground(Color.red);
           jPanelnum1.setBackground(Color.red);
         }
         if(seg==38){
         jPanelnum32.setBackground(Color.red);
         jPanelnum16.setBackground(Color.black);
           jPanelnum8.setBackground(Color.black);
          jPanelnum4.setBackground(Color.red);
           jPanelnum2.setBackground(Color.red);
             jPanelnum1.setBackground(Color.black);
         }
         if(seg==40){
         jPanelnum32.setBackground(Color.red);
         jPanelnum16.setBackground(Color.black);
          jPanelnum8.setBackground(Color.red);
          jPanelnum4.setBackground(Color.black);
          jPanelnum2.setBackground(Color.black);
          jPanelnum1.setBackground(Color.black);
          
         }
         if(seg==41){
         jPanelnum32.setBackground(Color.red);
         jPanelnum16.setBackground(Color.black);
          jPanelnum8.setBackground(Color.red);
          jPanelnum4.setBackground(Color.black);
          jPanelnum2.setBackground(Color.black);
          jPanelnum1.setBackground(Color.red);
         }
         if(seg==42){
          jPanelnum32.setBackground(Color.red);
          jPanelnum16.setBackground(Color.black);
          jPanelnum8.setBackground(Color.red);
          jPanelnum4.setBackground(Color.black);
          jPanelnum2.setBackground(Color.red);
          jPanelnum1.setBackground(Color.black);
         }
         if(seg==43){
           jPanelnum32.setBackground(Color.red);
           jPanelnum16.setBackground(Color.black);
          jPanelnum8.setBackground(Color.red);
          jPanelnum4.setBackground(Color.black);
          jPanelnum2.setBackground(Color.red);
          jPanelnum1.setBackground(Color.red);
         }
         if(seg==44){
              jPanelnum32.setBackground(Color.red);
              jPanelnum16.setBackground(Color.black);
          jPanelnum8.setBackground(Color.red);
          jPanelnum4.setBackground(Color.red);
          jPanelnum2.setBackground(Color.black);
          jPanelnum1.setBackground(Color.black);
         }
         if(seg==45){
             jPanelnum32.setBackground(Color.red);
             jPanelnum16.setBackground(Color.black);
          jPanelnum8.setBackground(Color.red);
          jPanelnum4.setBackground(Color.red);
          jPanelnum2.setBackground(Color.black);
          jPanelnum1.setBackground(Color.red);
         }
         if(seg==46){
                jPanelnum32.setBackground(Color.red);
                jPanelnum16.setBackground(Color.black);
          jPanelnum8.setBackground(Color.red);
          jPanelnum4.setBackground(Color.red);
          jPanelnum2.setBackground(Color.red);
          jPanelnum1.setBackground(Color.black);
         }
         if(seg==47){
           jPanelnum32.setBackground(Color.red);
           jPanelnum16.setBackground(Color.black);
          jPanelnum8.setBackground(Color.red);
          jPanelnum4.setBackground(Color.red);
          jPanelnum2.setBackground(Color.red);
          jPanelnum1.setBackground(Color.red);
         }
         if(seg==48){
            jPanelnum32.setBackground(Color.red);
          jPanelnum16.setBackground(Color.red);
          jPanelnum8.setBackground(Color.black);
          jPanelnum4.setBackground(Color.black);
          jPanelnum2.setBackground(Color.black);
          jPanelnum1.setBackground(Color.black);
     
         }
         if(seg==49){
          jPanelnum32.setBackground(Color.red);
          jPanelnum16.setBackground(Color.red);
          jPanelnum8.setBackground(Color.black);
          jPanelnum4.setBackground(Color.black);
          jPanelnum2.setBackground(Color.black);
          jPanelnum1.setBackground(Color.red);
         }
         if(seg==50){
         jPanelnum32.setBackground(Color.red);
         jPanelnum16.setBackground(Color.red);
         jPanelnum8.setBackground(Color.black);
         jPanelnum4.setBackground(Color.black);
         jPanelnum2.setBackground(Color.red);
         jPanelnum1.setBackground(Color.black);
         }
         if(seg==51){
         jPanelnum32.setBackground(Color.red);
         jPanelnum16.setBackground(Color.red);
         jPanelnum8.setBackground(Color.black);
         jPanelnum4.setBackground(Color.black);
         jPanelnum2.setBackground(Color.red);
         jPanelnum1.setBackground(Color.red);
         }
         if(seg==52){
             jPanelnum32.setBackground(Color.red);
         jPanelnum16.setBackground(Color.red);
         jPanelnum8.setBackground(Color.black);
         jPanelnum4.setBackground(Color.red);
         jPanelnum2.setBackground(Color.black);
         jPanelnum1.setBackground(Color.black);
       
         }
         if(seg==53){
             jPanelnum32.setBackground(Color.red);
         jPanelnum16.setBackground(Color.red);
         jPanelnum8.setBackground(Color.black);
         jPanelnum4.setBackground(Color.red);
         jPanelnum2.setBackground(Color.black);
         jPanelnum1.setBackground(Color.red);
         }
         if(seg==54){
         jPanelnum32.setBackground(Color.red);
         jPanelnum16.setBackground(Color.red);
         jPanelnum8.setBackground(Color.black);
         jPanelnum4.setBackground(Color.red);
         jPanelnum2.setBackground(Color.red);
         jPanelnum1.setBackground(Color.black);
         }
         if(seg==55){
                jPanelnum32.setBackground(Color.red);
         jPanelnum16.setBackground(Color.red);
         jPanelnum8.setBackground(Color.black);
         jPanelnum4.setBackground(Color.red);
         jPanelnum2.setBackground(Color.red);
         jPanelnum1.setBackground(Color.red);
         }
         if(seg==56){
          jPanelnum32.setBackground(Color.red);
         jPanelnum16.setBackground(Color.red);
         jPanelnum8.setBackground(Color.red);
         jPanelnum4.setBackground(Color.black);
         jPanelnum2.setBackground(Color.black);
         jPanelnum1.setBackground(Color.black);
         }
         if(seg==57){
         jPanelnum32.setBackground(Color.red);
         jPanelnum16.setBackground(Color.red);
         jPanelnum8.setBackground(Color.red);
         jPanelnum4.setBackground(Color.black);
         jPanelnum2.setBackground(Color.black);
          jPanelnum1.setBackground(Color.red);
         }
         if(seg==58){
           jPanelnum32.setBackground(Color.red);
         jPanelnum16.setBackground(Color.red);
         jPanelnum8.setBackground(Color.red);
         jPanelnum4.setBackground(Color.black);
         jPanelnum2.setBackground(Color.red);
         jPanelnum1.setBackground(Color.black);
         }
         if(seg==59){
          jPanelnum32.setBackground(Color.red);
         jPanelnum16.setBackground(Color.red);
         jPanelnum8.setBackground(Color.red);
         jPanelnum4.setBackground(Color.black);
         jPanelnum2.setBackground(Color.red);
         jPanelnum1.setBackground(Color.red);
         }
         if(seg==60){
        jPanelnum32.setBackground(Color.red);
         jPanelnum16.setBackground(Color.red);
         jPanelnum8.setBackground(Color.red);
         jPanelnum4.setBackground(Color.red);
         jPanelnum2.setBackground(Color.black);
         jPanelnum1.setBackground(Color.black);
         
         }
     }
     
   
     }
       

  
 


